write_readme_task:
  description: >
    Con la información proporcionada sobre los archivos del proyecto, 
    redacta un README.md que incluya una descripción general del proyecto,
    una lista de archivos clave y sus propósitos.
    Incluye informacion de instalacion, uso y configuracion utilizando poetry y pyproject.toml
  expected_output: >
    Un archivo README.md detallado y bien estructurado.
  agent: writer_agent

translate_readme_task:
  description: >
    Tomar el contenido generado en el archivo README.md y traducirlo al español. Mantener precisión técnica en la traducción para que sea comprensible y adecuada para usuarios hispanohablantes.
  expected_output: >
    Un archivo README_es.md con el contenido del README.md traducido al español, preservando la claridad y el contexto técnico.
  agent: translator_agent 